version: "3.3"
services:
  api:
    container_name: config-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - database
  database:
    container_name: database
    image: ${DOCKER_REGISTRY-}config-server-db
    build:
      context: sql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"